// COCO-SSD 80 class labels with multi-language translations
const LABELS = {
  en: {
    person: "Person", bicycle: "Bicycle", car: "Car", motorcycle: "Motorcycle",
    airplane: "Airplane", bus: "Bus", train: "Train", truck: "Truck",
    boat: "Boat", "traffic light": "Traffic Light", "fire hydrant": "Fire Hydrant",
    "stop sign": "Stop Sign", "parking meter": "Parking Meter", bench: "Bench",
    bird: "Bird", cat: "Cat", dog: "Dog", horse: "Horse", sheep: "Sheep",
    cow: "Cow", elephant: "Elephant", bear: "Bear", zebra: "Zebra",
    giraffe: "Giraffe", backpack: "Backpack", umbrella: "Umbrella",
    handbag: "Handbag", tie: "Tie", suitcase: "Suitcase", frisbee: "Frisbee",
    skis: "Skis", snowboard: "Snowboard", "sports ball": "Sports Ball",
    kite: "Kite", "baseball bat": "Baseball Bat", "baseball glove": "Baseball Glove",
    skateboard: "Skateboard", surfboard: "Surfboard", "tennis racket": "Tennis Racket",
    bottle: "Bottle", "wine glass": "Wine Glass", cup: "Cup", fork: "Fork",
    knife: "Knife", spoon: "Spoon", bowl: "Bowl", banana: "Banana", apple: "Apple",
    sandwich: "Sandwich", orange: "Orange", broccoli: "Broccoli", carrot: "Carrot",
    "hot dog": "Hot Dog", pizza: "Pizza", donut: "Donut", cake: "Cake",
    chair: "Chair", couch: "Couch", "potted plant": "Potted Plant", bed: "Bed",
    "dining table": "Dining Table", toilet: "Toilet", tv: "TV",
    laptop: "Laptop", mouse: "Mouse", remote: "Remote", keyboard: "Keyboard",
    "cell phone": "Cell Phone", microwave: "Microwave", oven: "Oven",
    toaster: "Toaster", sink: "Sink", refrigerator: "Refrigerator", book: "Book",
    clock: "Clock", vase: "Vase", scissors: "Scissors", "teddy bear": "Teddy Bear",
    "hair drier": "Hair Drier", toothbrush: "Toothbrush"
  },
  "zh-TW": {
    person: "人", bicycle: "腳踏車", car: "汽車", motorcycle: "機車",
    airplane: "飛機", bus: "公車", train: "火車", truck: "卡車",
    boat: "船", "traffic light": "紅綠燈", "fire hydrant": "消防栓",
    "stop sign": "停止標誌", "parking meter": "停車計時器", bench: "長椅",
    bird: "鳥", cat: "貓", dog: "狗", horse: "馬", sheep: "羊",
    cow: "牛", elephant: "大象", bear: "熊", zebra: "斑馬",
    giraffe: "長頸鹿", backpack: "背包", umbrella: "雨傘",
    handbag: "手提包", tie: "領帶", suitcase: "行李箱", frisbee: "飛盤",
    skis: "滑雪板", snowboard: "單板滑雪", "sports ball": "運動球",
    kite: "風箏", "baseball bat": "棒球棒", "baseball glove": "棒球手套",
    skateboard: "滑板", surfboard: "衝浪板", "tennis racket": "網球拍",
    bottle: "瓶子", "wine glass": "酒杯", cup: "杯子", fork: "叉子",
    knife: "刀子", spoon: "湯匙", bowl: "碗", banana: "香蕉", apple: "蘋果",
    sandwich: "三明治", orange: "柳橙", broccoli: "花椰菜", carrot: "紅蘿蔔",
    "hot dog": "熱狗", pizza: "披薩", donut: "甜甜圈", cake: "蛋糕",
    chair: "椅子", couch: "沙發", "potted plant": "盆栽", bed: "床",
    "dining table": "餐桌", toilet: "馬桶", tv: "電視",
    laptop: "筆電", mouse: "滑鼠", remote: "遙控器", keyboard: "鍵盤",
    "cell phone": "手機", microwave: "微波爐", oven: "烤箱",
    toaster: "烤麵包機", sink: "水槽", refrigerator: "冰箱", book: "書",
    clock: "時鐘", vase: "花瓶", scissors: "剪刀", "teddy bear": "泰迪熊",
    "hair drier": "吹風機", toothbrush: "牙刷"
  },
  "zh-CN": {
    person: "人", bicycle: "自行车", car: "汽车", motorcycle: "摩托车",
    airplane: "飞机", bus: "公共汽车", train: "火车", truck: "卡车",
    boat: "船", "traffic light": "红绿灯", "fire hydrant": "消防栓",
    "stop sign": "停止标志", "parking meter": "停车计时器", bench: "长椅",
    bird: "鸟", cat: "猫", dog: "狗", horse: "马", sheep: "羊",
    cow: "牛", elephant: "大象", bear: "熊", zebra: "斑马",
    giraffe: "长颈鹿", backpack: "背包", umbrella: "雨伞",
    handbag: "手提包", tie: "领带", suitcase: "行李箱", frisbee: "飞盘",
    skis: "滑雪板", snowboard: "单板滑雪", "sports ball": "运动球",
    kite: "风筝", "baseball bat": "棒球棒", "baseball glove": "棒球手套",
    skateboard: "滑板", surfboard: "冲浪板", "tennis racket": "网球拍",
    bottle: "瓶子", "wine glass": "酒杯", cup: "杯子", fork: "叉子",
    knife: "刀子", spoon: "汤匙", bowl: "碗", banana: "香蕉", apple: "苹果",
    sandwich: "三明治", orange: "橘子", broccoli: "花椰菜", carrot: "胡萝卜",
    "hot dog": "热狗", pizza: "比萨", donut: "甜甜圈", cake: "蛋糕",
    chair: "椅子", couch: "沙发", "potted plant": "盆栽", bed: "床",
    "dining table": "餐桌", toilet: "马桶", tv: "电视",
    laptop: "笔记本", mouse: "鼠标", remote: "遥控器", keyboard: "键盘",
    "cell phone": "手机", microwave: "微波炉", oven: "烤箱",
    toaster: "烤面包机", sink: "水槽", refrigerator: "冰箱", book: "书",
    clock: "时钟", vase: "花瓶", scissors: "剪刀", "teddy bear": "泰迪熊",
    "hair drier": "吹风机", toothbrush: "牙刷"
  },
  ja: {
    person: "人", bicycle: "自転車", car: "車", motorcycle: "バイク",
    airplane: "飛行機", bus: "バス", train: "電車", truck: "トラック",
    boat: "ボート", "traffic light": "信号機", "fire hydrant": "消火栓",
    "stop sign": "一時停止", "parking meter": "パーキングメーター", bench: "ベンチ",
    bird: "鳥", cat: "猫", dog: "犬", horse: "馬", sheep: "羊",
    cow: "牛", elephant: "象", bear: "熊", zebra: "シマウマ",
    giraffe: "キリン", backpack: "リュック", umbrella: "傘",
    handbag: "ハンドバッグ", tie: "ネクタイ", suitcase: "スーツケース", frisbee: "フリスビー",
    skis: "スキー", snowboard: "スノーボード", "sports ball": "ボール",
    kite: "凧", "baseball bat": "バット", "baseball glove": "グローブ",
    skateboard: "スケートボード", surfboard: "サーフボード", "tennis racket": "テニスラケット",
    bottle: "ボトル", "wine glass": "ワイングラス", cup: "カップ", fork: "フォーク",
    knife: "ナイフ", spoon: "スプーン", bowl: "ボウル", banana: "バナナ", apple: "リンゴ",
    sandwich: "サンドイッチ", orange: "オレンジ", broccoli: "ブロッコリー", carrot: "ニンジン",
    "hot dog": "ホットドッグ", pizza: "ピザ", donut: "ドーナツ", cake: "ケーキ",
    chair: "椅子", couch: "ソファ", "potted plant": "植木", bed: "ベッド",
    "dining table": "テーブル", toilet: "トイレ", tv: "テレビ",
    laptop: "ノートPC", mouse: "マウス", remote: "リモコン", keyboard: "キーボード",
    "cell phone": "スマホ", microwave: "電子レンジ", oven: "オーブン",
    toaster: "トースター", sink: "シンク", refrigerator: "冷蔵庫", book: "本",
    clock: "時計", vase: "花瓶", scissors: "ハサミ", "teddy bear": "テディベア",
    "hair drier": "ドライヤー", toothbrush: "歯ブラシ"
  },
  ko: {
    person: "사람", bicycle: "자전거", car: "자동차", motorcycle: "오토바이",
    airplane: "비행기", bus: "버스", train: "기차", truck: "트럭",
    boat: "보트", "traffic light": "신호등", "fire hydrant": "소화전",
    "stop sign": "정지 표지판", "parking meter": "주차 미터기", bench: "벤치",
    bird: "새", cat: "고양이", dog: "개", horse: "말", sheep: "양",
    cow: "소", elephant: "코끼리", bear: "곰", zebra: "얼룩말",
    giraffe: "기린", backpack: "배낭", umbrella: "우산",
    handbag: "핸드백", tie: "넥타이", suitcase: "여행가방", frisbee: "프리스비",
    skis: "스키", snowboard: "스노보드", "sports ball": "공",
    kite: "연", "baseball bat": "야구방망이", "baseball glove": "야구글러브",
    skateboard: "스케이트보드", surfboard: "서프보드", "tennis racket": "테니스라켓",
    bottle: "병", "wine glass": "와인잔", cup: "컵", fork: "포크",
    knife: "칼", spoon: "숟가락", bowl: "그릇", banana: "바나나", apple: "사과",
    sandwich: "샌드위치", orange: "오렌지", broccoli: "브로콜리", carrot: "당근",
    "hot dog": "핫도그", pizza: "피자", donut: "도넛", cake: "케이크",
    chair: "의자", couch: "소파", "potted plant": "화분", bed: "침대",
    "dining table": "식탁", toilet: "변기", tv: "TV",
    laptop: "노트북", mouse: "마우스", remote: "리모컨", keyboard: "키보드",
    "cell phone": "휴대폰", microwave: "전자레인지", oven: "오븐",
    toaster: "토스터", sink: "싱크대", refrigerator: "냉장고", book: "책",
    clock: "시계", vase: "꽃병", scissors: "가위", "teddy bear": "테디베어",
    "hair drier": "드라이기", toothbrush: "칫솔"
  },
  es: {
    person: "Persona", bicycle: "Bicicleta", car: "Coche", motorcycle: "Moto",
    airplane: "Avión", bus: "Autobús", train: "Tren", truck: "Camión",
    boat: "Barco", "traffic light": "Semáforo", "fire hydrant": "Hidrante",
    "stop sign": "Señal de Stop", "parking meter": "Parquímetro", bench: "Banco",
    bird: "Pájaro", cat: "Gato", dog: "Perro", horse: "Caballo", sheep: "Oveja",
    cow: "Vaca", elephant: "Elefante", bear: "Oso", zebra: "Cebra",
    giraffe: "Jirafa", backpack: "Mochila", umbrella: "Paraguas",
    handbag: "Bolso", tie: "Corbata", suitcase: "Maleta", frisbee: "Frisbee",
    skis: "Esquís", snowboard: "Snowboard", "sports ball": "Pelota",
    kite: "Cometa", "baseball bat": "Bate", "baseball glove": "Guante de béisbol",
    skateboard: "Monopatín", surfboard: "Tabla de surf", "tennis racket": "Raqueta",
    bottle: "Botella", "wine glass": "Copa de vino", cup: "Taza", fork: "Tenedor",
    knife: "Cuchillo", spoon: "Cuchara", bowl: "Cuenco", banana: "Plátano", apple: "Manzana",
    sandwich: "Sándwich", orange: "Naranja", broccoli: "Brócoli", carrot: "Zanahoria",
    "hot dog": "Perrito caliente", pizza: "Pizza", donut: "Dona", cake: "Pastel",
    chair: "Silla", couch: "Sofá", "potted plant": "Planta en maceta", bed: "Cama",
    "dining table": "Mesa de comedor", toilet: "Inodoro", tv: "Televisión",
    laptop: "Portátil", mouse: "Ratón", remote: "Control remoto", keyboard: "Teclado",
    "cell phone": "Teléfono móvil", microwave: "Microondas", oven: "Horno",
    toaster: "Tostadora", sink: "Fregadero", refrigerator: "Nevera", book: "Libro",
    clock: "Reloj", vase: "Jarrón", scissors: "Tijeras", "teddy bear": "Oso de peluche",
    "hair drier": "Secador", toothbrush: "Cepillo de dientes"
  },
  fr: {
    person: "Personne", bicycle: "Vélo", car: "Voiture", motorcycle: "Moto",
    airplane: "Avion", bus: "Bus", train: "Train", truck: "Camion",
    boat: "Bateau", "traffic light": "Feu de circulation", "fire hydrant": "Bouche d'incendie",
    "stop sign": "Panneau Stop", "parking meter": "Parcmètre", bench: "Banc",
    bird: "Oiseau", cat: "Chat", dog: "Chien", horse: "Cheval", sheep: "Mouton",
    cow: "Vache", elephant: "Éléphant", bear: "Ours", zebra: "Zèbre",
    giraffe: "Girafe", backpack: "Sac à dos", umbrella: "Parapluie",
    handbag: "Sac à main", tie: "Cravate", suitcase: "Valise", frisbee: "Frisbee",
    skis: "Skis", snowboard: "Snowboard", "sports ball": "Ballon",
    kite: "Cerf-volant", "baseball bat": "Batte", "baseball glove": "Gant de baseball",
    skateboard: "Skateboard", surfboard: "Planche de surf", "tennis racket": "Raquette",
    bottle: "Bouteille", "wine glass": "Verre à vin", cup: "Tasse", fork: "Fourchette",
    knife: "Couteau", spoon: "Cuillère", bowl: "Bol", banana: "Banane", apple: "Pomme",
    sandwich: "Sandwich", orange: "Orange", broccoli: "Brocoli", carrot: "Carotte",
    "hot dog": "Hot-dog", pizza: "Pizza", donut: "Beignet", cake: "Gâteau",
    chair: "Chaise", couch: "Canapé", "potted plant": "Plante en pot", bed: "Lit",
    "dining table": "Table à manger", toilet: "Toilettes", tv: "Télévision",
    laptop: "Ordinateur portable", mouse: "Souris", remote: "Télécommande", keyboard: "Clavier",
    "cell phone": "Téléphone portable", microwave: "Micro-ondes", oven: "Four",
    toaster: "Grille-pain", sink: "Évier", refrigerator: "Réfrigérateur", book: "Livre",
    clock: "Horloge", vase: "Vase", scissors: "Ciseaux", "teddy bear": "Nounours",
    "hair drier": "Sèche-cheveux", toothbrush: "Brosse à dents"
  },
  de: {
    person: "Person", bicycle: "Fahrrad", car: "Auto", motorcycle: "Motorrad",
    airplane: "Flugzeug", bus: "Bus", train: "Zug", truck: "LKW",
    boat: "Boot", "traffic light": "Ampel", "fire hydrant": "Hydrant",
    "stop sign": "Stoppschild", "parking meter": "Parkuhr", bench: "Bank",
    bird: "Vogel", cat: "Katze", dog: "Hund", horse: "Pferd", sheep: "Schaf",
    cow: "Kuh", elephant: "Elefant", bear: "Bär", zebra: "Zebra",
    giraffe: "Giraffe", backpack: "Rucksack", umbrella: "Regenschirm",
    handbag: "Handtasche", tie: "Krawatte", suitcase: "Koffer", frisbee: "Frisbee",
    skis: "Skier", snowboard: "Snowboard", "sports ball": "Ball",
    kite: "Drachen", "baseball bat": "Baseballschläger", "baseball glove": "Baseballhandschuh",
    skateboard: "Skateboard", surfboard: "Surfbrett", "tennis racket": "Tennisschläger",
    bottle: "Flasche", "wine glass": "Weinglas", cup: "Tasse", fork: "Gabel",
    knife: "Messer", spoon: "Löffel", bowl: "Schüssel", banana: "Banane", apple: "Apfel",
    sandwich: "Sandwich", orange: "Orange", broccoli: "Brokkoli", carrot: "Karotte",
    "hot dog": "Hot Dog", pizza: "Pizza", donut: "Donut", cake: "Kuchen",
    chair: "Stuhl", couch: "Sofa", "potted plant": "Topfpflanze", bed: "Bett",
    "dining table": "Esstisch", toilet: "Toilette", tv: "Fernseher",
    laptop: "Laptop", mouse: "Maus", remote: "Fernbedienung", keyboard: "Tastatur",
    "cell phone": "Handy", microwave: "Mikrowelle", oven: "Ofen",
    toaster: "Toaster", sink: "Waschbecken", refrigerator: "Kühlschrank", book: "Buch",
    clock: "Uhr", vase: "Vase", scissors: "Schere", "teddy bear": "Teddybär",
    "hair drier": "Haartrockner", toothbrush: "Zahnbürste"
  }
};

const LANGUAGE_NAMES = {
  en: "English",
  "zh-TW": "繁體中文",
  "zh-CN": "简体中文",
  ja: "日本語",
  ko: "한국어",
  es: "Español",
  fr: "Français",
  de: "Deutsch"
};

function getLabel(classKey, lang) {
  const dict = LABELS[lang] || LABELS["en"];
  const enDict = LABELS["en"];
  const label = dict[classKey] || enDict[classKey] || classKey;
  if (lang !== "en" && dict[classKey]) {
    return `${enDict[classKey] || classKey} / ${label}`;
  }
  return label;
}
